set -g prefix C-a
unbind C-b
bind C-a send-prefix

set -g mouse on
set -g history-limit 10000
set -g mode-keys vi
set -g base-index 1
set -g pane-base-index 1
set -g renumber-windows on
set -g default-terminal "screen-256color"
set -as terminal-features ",xterm-256color:RGB"
set -g extended-keys on
set -as terminal-features ",xterm-ghostty:RGB,extkeys"

unbind r
bind r source-file ~/.tmux.conf \; display-message "Tmux reloaded"

bind | split-window -h -c "#{pane_current_path}"
bind - split-window -v -c "#{pane_current_path}"
bind c new-window -c "#{pane_current_path}"

bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

bind -r H resize-pane -L 5
bind -r J resize-pane -D 2
bind -r K resize-pane -U 2
bind -r L resize-pane -R 5

bind -r n next-window
bind -r p previous-window
bind w choose-window
bind s choose-session
bind R command-prompt -I "#W" "rename-window '%%'"

set -g status on
set -g status-interval 5
set -g status-justify left
set -g status-left-length 60
set -g status-right-length 60
set -g status-style "bg=#363a4f"
set -g status-left-style "bg=#363a4f"
set -g status-right-style "bg=#363a4f"

set -g @catppuccin_flavor "macchiato"
set -g @catppuccin_window_status_style "rounded"
set -g @catppuccin_window_default_text "#W"
set -g @catppuccin_window_current_text "#W"
set -g @catppuccin_status_background "#363a4f"
set -g @catppuccin_status_left_modules "session"
set -g @catppuccin_status_right_modules "application uptime"
set -g @catppuccin_status_fill "icon"

set -g @catppuccin_date_time_text "%a %d %b %H:%M"

set -g @catppuccin_application_icon "#{?#{m:#{pane_current_command},^(n?vim)$}, ,#{?#{m:#{pane_current_command},^opencode$},󰚩 ,#{?#{m:#{pane_current_command},^(zsh|bash|fish|tmux)$}, , }}}"
set -g @catppuccin_status_application "#[fg=#{@catppuccin_application_color}]#{E:@catppuccin_application_icon} #[fg=#{@thm_fg}]#{pane_current_command}"

set -g status-left "#[fg=#F38BA8,bg=#363a4f]#[fg=#373A4E,bg=#F38BA8] #S #[fg=#F38BA8,bg=#363a4f] "
set -g status-right "#{E:@catppuccin_status_application} #[fg=#A6E3A1]#{E:@catppuccin_status_uptime} #[fg=#74C7EC,bg=#373a4e]#[fg=#373A4E,bg=#74C7EC] %a %d %b %H:%M #[fg=#74C7EC,bg=#363a4f]"



bind-key -T copy-mode-vi v send -X begin-selection
unbind -T copy-mode-vi MouseDragEnd1Pane
if-shell "uname | grep -qi darwin" "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'pbcopy'"
if-shell "uname | grep -qi linux && command -v wl-copy >/dev/null 2>&1" "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'wl-copy'"
if-shell "uname | grep -qi linux && ! command -v wl-copy >/dev/null 2>&1 && command -v xclip >/dev/null 2>&1" "bind-key -T copy-mode-vi y send-keys -X copy-pipe-and-cancel 'xclip -in -selection clipboard'"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux#v1.0.0'

run '~/.tmux/plugins/tpm/tpm'
